# Briefest introduction to NumPy and SciPy 

In [1]:
import numpy as np
import scipy as sp

## Key concept: *arrays*
The key datastructure in NumPy and SciPy are arrays — multidimensional arrays of a single data type (e.g. 64-bit float).

## Array creation

There are many ways to create arrays, e.g.:

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Indexing and Slicing

Can use Python indexing and slicing as with lists:

In [3]:
a[5]

5

In [4]:
a[5:]

array([5, 6, 7, 8, 9])

In [5]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

2D arrays

In [6]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
b[1:,1:]

array([[4, 5],
       [7, 8]])

## Aggregation functions 

In [8]:
a.sum(), a.mean(), a.std()

(45, 4.5, 2.8722813232690143)

## Array operations

> "NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape"

In [9]:
a = np.ones(10)
b = np.random.randn(10)
print(a)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[-0.07260688 -0.46327498 -1.44484783  1.37284134  1.44142756 -0.38208644
  0.73498442 -0.79924088 -0.70612214  0.48158412]


In [10]:
a+b

array([ 0.92739312,  0.53672502, -0.44484783,  2.37284134,  2.44142756,
        0.61791356,  1.73498442,  0.20075912,  0.29387786,  1.48158412])

In [11]:
np.exp(b)

array([0.92996635, 0.62921959, 0.23578195, 3.94654826, 4.2267254 ,
       0.68243606, 2.08544949, 0.44967019, 0.49355442, 1.61863648])

## 'Broadcasting'

> "The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation."

In [12]:
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
2*a

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [14]:
a = np.random.randint(0, 10, (5,10))

In [15]:
a

array([[4, 7, 0, 5, 9, 7, 7, 5, 4, 7],
       [6, 2, 4, 2, 1, 7, 2, 2, 8, 8],
       [1, 4, 3, 7, 4, 6, 9, 1, 6, 9],
       [3, 1, 1, 1, 1, 1, 1, 1, 7, 3],
       [6, 9, 4, 6, 2, 6, 2, 1, 2, 5]])

In [16]:
a.shape

(5, 10)

In [17]:
10*a

array([[40, 70,  0, 50, 90, 70, 70, 50, 40, 70],
       [60, 20, 40, 20, 10, 70, 20, 20, 80, 80],
       [10, 40, 30, 70, 40, 60, 90, 10, 60, 90],
       [30, 10, 10, 10, 10, 10, 10, 10, 70, 30],
       [60, 90, 40, 60, 20, 60, 20, 10, 20, 50]])

In [18]:
b = np.random.randint(0, 2, 10)
b

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 1])

Row wise multiplication:

In [19]:
a*b

array([[0, 0, 0, 5, 0, 7, 0, 5, 4, 7],
       [0, 0, 4, 2, 0, 7, 0, 2, 8, 8],
       [0, 0, 3, 7, 0, 6, 0, 1, 6, 9],
       [0, 0, 1, 1, 0, 1, 0, 1, 7, 3],
       [0, 0, 4, 6, 0, 6, 0, 1, 2, 5]])

Column wise?

In [20]:
b = np.random.randint(0, 2, 5)
b

array([1, 1, 0, 1, 0])

In [21]:
a*b

ValueError: operands could not be broadcast together with shapes (5,10) (5,) 

First, turn `b` into a column:

In [22]:
b.reshape(5,1)

array([[1],
       [1],
       [0],
       [1],
       [0]])

...and multiply:

In [23]:
a*b.reshape(5,1)

array([[4, 7, 0, 5, 9, 7, 7, 5, 4, 7],
       [6, 2, 4, 2, 1, 7, 2, 2, 8, 8],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 1, 1, 1, 1, 1, 1, 1, 7, 3],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Matrix multiplication

In [24]:
a = np.random.randint(0, 10, (3,2))
b = np.random.randint(0, 10, (2,4))
print(a)
print(b)

[[5 2]
 [3 7]
 [9 2]]
[[3 2 9 9]
 [7 9 3 7]]


In [25]:
a @ b

array([[29, 28, 51, 59],
       [58, 69, 48, 76],
       [41, 36, 87, 95]])

## NumPy and SciPy are fast 

### Spearman rank correlation example

In [26]:
np.set_printoptions(precision=2, suppress=True, linewidth=120)

In [27]:
a = np.random.randn(3,10)
a

array([[-0.57,  0.48, -0.06, -0.17,  0.28,  0.66,  1.51,  0.01,  1.25, -0.82],
       [-2.53, -0.34,  1.24, -1.35, -0.75,  1.26,  1.35,  0.09,  0.6 , -1.05],
       [-0.52,  1.52, -0.42, -0.53,  0.34, -1.03, -0.22, -2.15,  0.58,  0.48]])

In [28]:
from scipy.stats import spearmanr

In [29]:
results = spearmanr(a, axis=1)

In [30]:
results.correlation

array([[ 1.  ,  0.78,  0.2 ],
       [ 0.78,  1.  , -0.04],
       [ 0.2 , -0.04,  1.  ]])

A larger problem:

In [31]:
a = np.random.randn(1000,10000)
results = spearmanr(a, axis=1)
results.correlation[:8,:8]

array([[ 1.  , -0.01,  0.  , -0.02,  0.01, -0.01, -0.01, -0.01],
       [-0.01,  1.  , -0.  ,  0.01,  0.  ,  0.  ,  0.01, -0.01],
       [ 0.  , -0.  ,  1.  , -0.01, -0.  , -0.  ,  0.  ,  0.02],
       [-0.02,  0.01, -0.01,  1.  , -0.01, -0.  ,  0.  ,  0.01],
       [ 0.01,  0.  , -0.  , -0.01,  1.  ,  0.01,  0.01,  0.  ],
       [-0.01,  0.  , -0.  , -0.  ,  0.01,  1.  ,  0.  , -0.  ],
       [-0.01,  0.01,  0.  ,  0.  ,  0.01,  0.  ,  1.  ,  0.02],
       [-0.01, -0.01,  0.02,  0.01,  0.  , -0.  ,  0.02,  1.  ]])

## NumPy and SciPy are multi-threaded

NumPy and SciPy make use of parallel threads to speed up performance. This is great. But, on a shared cluster (like Eddie) it is important to only use the number of CPU cores that have been requested. You can control this with the `OMP_NUM_THREADS` and `MKL_NUM_THREADS` environment variables. Put them into your job scripts:

```
#!/bin/bash

# Grid Engine options
#$ -cwd
#$ -pe sharedmem 4
#...

# $NSLOTS is set by Grid Engine to the number of slots (cores) requested
# in this example it will be set to 4 (-pe sharedmem 4) 
export OMP_NUM_THREADS=$NSLOTS
export MKL_NUM_THREADS=$NSLOTS

python my_analysis.py
```

Or if using `qlogin` you have to remember how many slots you requested: 

```
$ qlogin -pe sharedmem 2 -l h_vmem=4G
...
$ export OMP_NUM_THREADS=2
$ export MKL_NUM_THREADS=2
$ python my_analysis.py
```